name: Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: your-docker-username/your-app-name:latest  # Replace with your Docker Hub username and app name

      - name: Deploy to Railway
        uses: railwayapp/railway-action@v1
        with:
          railway_api_key: ${{ secrets.RAILWAY_API_KEY }}
          railway_project_id: ${{ secrets.RAILWAY_PROJECT_ID }}
